### ISSUE TITLE
ServletHttpHandler does not serve static resources

### ISSUE THREAD

**Issue by lfielke** [micronaut-projects/micronaut-servlet#191]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] ~Example that reproduces the problem uploaded to Github.~ _Omitted because the issue can be reproduced in a few lines of shell_
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create an app using the mn command line tool, enable static resources and put a text file to be served as a static resource:

```
mn create-app -f=tomcat-server mn-staticres-bug
cd mn-staticres-bug

mkdir src/main/resources/public
echo Hello > src/main/resources/public/hello.txt

cat << EOF > src/main/resources/application.yml
micronaut:
  application:
    name: mnStaticresBug
  router:
    static-resources:
      default:
        paths: "classpath:public"
EOF

./gradlew run
```

In another terminal:
```
curl http://localhost:8080/hello.txt
```

Stacktrace into `ServletHttpHandler`

```
service:181, ServletHttpHandler (io.micronaut.servlet.http)
service:53, DefaultServletHttpHandler (io.micronaut.servlet.engine)
service:66, DefaultMicronautServlet (io.micronaut.servlet.engine)
service:750, HttpServlet (javax.servlet.http)
internalDoFilter:231, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
invoke:202, StandardWrapperValve (org.apache.catalina.core)
invoke:97, StandardContextValve (org.apache.catalina.core)
invoke:541, AuthenticatorBase (org.apache.catalina.authenticator)
invoke:143, StandardHostValve (org.apache.catalina.core)
invoke:92, ErrorReportValve (org.apache.catalina.valves)
invoke:78, StandardEngineValve (org.apache.catalina.core)
service:343, CoyoteAdapter (org.apache.catalina.connector)
service:374, Http11Processor (org.apache.coyote.http11)
process:65, AbstractProcessorLight (org.apache.coyote)
process:868, AbstractProtocol$ConnectionHandler (org.apache.coyote)
doRun:1590, NioEndpoint$SocketProcessor (org.apache.tomcat.util.net)
run:49, SocketProcessorBase (org.apache.tomcat.util.net)
runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
run:61, TaskThread$WrappingRunnable (org.apache.tomcat.util.threads)
run:834, Thread (java.lang)
```

Note that no code paths in the `ServletHttpHandler#service` method attempt to look for static resources.

### Expected Behaviour

Expected to see the curl output the contents of the hello.txt file:

```
Hello
```

### Actual Behaviour

curl outputs the JSON error message not found:
```
{"message":"Not Found","_links":{"self":{"href":"/hello.txt","templated":false}}}
```

### Environment Information

- **Operating System**: Ubuntu 20.10
- **Micronaut Version:** v2.4.1
- **JDK Version:** OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.10)

### Example Application

GitHub link not provided since the instructions to reproduce are fairly trivial. Apologies if this is unacceptable, and I will provide a repo.

### Additional information

If I remove the `tomcat-server` feature, making Micronaut use it's Netty server, then using the same instructions above the Hello file is served as expected.

One difference I can see between the Netty `RoutingInBoundHandler` and the `io.micronaut.servlet.http.ServletHttpHandler` is that `ServletHttpHandler` never calls into `io.micronaut.web.router.resource.StaticResourceResolver#resolve`. The micronaut-servlet docs have an FAQ "How do I configure Static Resource handling for the embedded server?" pointing at the main HTTP docs, so I'd expect my sample to work the same on both Netty and Tomcat.

### Background and alternative solution

I'm looking to add Micronaut to an existing Java web app. This app is currently deployed on Tomcat and uses servlets directly, so I'm looking for a way to incrementally add Micronaut to the application to avoid a big bang rewrite.

This app currently uses Tomcat's DefaultServlet to serve static resources, and I'd be happy to keep doing that, but I couldn't work out a way to run Micronaut without it being mapped to `/**`, precluding the use of the Tomcat's DefaultServlet.

**Comment by patrickhousley-vml** [comment]
I just spent hours troubleshooting why my swagger docs and ui would not load. Revert back to netty and bam it works.

**Comment by graemerocher** [comment]
Servlet containers behave differently with regards to static resources, but it does seem we lack test coverage for Tomcat for this use case. The Jetty tests are operational https://github.com/micronaut-projects/micronaut-servlet/blob/master/http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyStaticResourceResolutionSpec.groovy

**Comment by patrickhousley-vml** [comment]
Is there any update for this issue?

**Comment by mattmoss** [comment]
Investigating. While jetty does reference the static resources as configured by `micronaut.router.static-resources.*` (and accessed via `ServletServerFactory.getStaticResourceConfigurations`, neither tomcat nor undertow do.

Adding this to my plate.

**Comment by mattmoss** [comment]
Side note: it seems if you configure the `/swagger` path before the `/swagger-ui` path, jetty does some string ops and fails to serve `/swagger-ui`.  Putting `/swagger-ui` first fixes, so there is some order sensitivity there.
